"""Standalone, local evaluation report; no network or plotting dependency."""

import csv
import json
from pathlib import Path


def write_evaluation(evaluation, output):
    output = Path(output)
    output.mkdir(parents=True, exist_ok=True)
    data_path, csv_path, html_path = (output / name for name in ("evaluation.json", "evaluation.csv", "evaluation.html"))
    data_path.write_text(json.dumps(evaluation, indent=2, ensure_ascii=False, allow_nan=False) + "\n")
    fields = ["component_id", "gpu_uuid", "workload", "contract", "group_id", "objective", "requested_graphics_mhz",
              "requested_memory_mhz", "achieved_sm_mhz", "geometry", "anchor_tags", "ncu_status", "valid_repeats",
              "rejected_repeats", "throughput", "rate_unit", "energy", "energy_unit", "energy_ci95", "objective_eligible", "objective_measurement_valid",
              "recommendation_status", "quality_issues", "eligibility_reasons", "dense_tensor_peak_fraction", "row_width", "pj_per_row",
              "measurement_diagnostics", "nonlinear_launch", "sfu_launch", "sfu_reference_delta", "sfu_reference_diagnostics",
              "experiment_role", "memory_stride_words", "memory_lane_stride_bytes", "memory_observed_sector_efficiency_pct",
              "memory_coalescing_energy_eligible", "energy_peak_population_eligible", "memory_access_geometry", "memory_coalescing"]
    with csv_path.open("w", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=fields); writer.writeheader()
        for c in evaluation["components"]:
            recommendations = {(r.get("group_id"), r["objective"]): r["status"] for r in c["recommendations"]}
            for p in c["points"]:
                for o, energy in p["energies"].items():
                    row = {**{key: p.get(key) for key in fields}, "component_id": c["component_id"],
                        "gpu_uuid": c["stratum"]["gpu_uuid"], "workload": c["stratum"]["workload"],
                        "contract": c["stratum"]["experiment_contract"], "objective": o,
                        "throughput": p["rate"] / c["units"]["rate_scale"] if p["rate"] is not None else None,
                        "rate_unit": c["units"]["rate_unit"], "energy": energy, "energy_unit": c["units"]["energy_unit"],
                        "energy_ci95": p["energy_ci95"][o], "objective_eligible": p["objective_eligible"][o],
                        "objective_measurement_valid": p["objective_measurement_valid"][o],
                        "eligibility_reasons": p.get("eligibility_reasons", {}).get(o, []),
                        "dense_tensor_peak_fraction": p.get("tensor_dense_peak_fraction"),
                        "pj_per_row": p.get("pj_per_row", {}).get(o),
                        "recommendation_status": recommendations.get((p["group_id"], o))}
                    writer.writerow({k: json.dumps(v, ensure_ascii=False) if isinstance(v, (list, dict)) else v for k, v in row.items()})
    # Untrusted names/metadata cannot close this script tag or create markup.
    payload = json.dumps(evaluation, ensure_ascii=False, allow_nan=False).replace("<", "\\u003c").replace("&", "\\u0026")
    html_path.write_text(_HTML.replace("__EVALUATION_DATA__", payload))
    return {"evaluation_json": str(data_path), "evaluation_csv": str(csv_path), "evaluation_html": str(html_path)}


_HTML = r'''<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>GPU component evaluation</title>
<style>
:root{font-family:system-ui,sans-serif;color:#17263c;background:#f4f6f9}body{max-width:1400px;margin:30px auto;padding:0 22px}h1{font-size:27px;margin-bottom:8px}h2{font-size:19px}p{line-height:1.6}.bar>div{min-width:0;max-width:100%}.bar>div[style*="flex:1"]{min-width:min(180px,100%)}.bar,.cards{display:flex;gap:16px;flex-wrap:wrap}.card,section{background:white;padding:18px;margin:14px 0;border:1px solid #dce2eb;border-radius:10px}.card{flex:1;min-width:160px}.value{font-size:21px;font-weight:600}select{max-width:100%;padding:8px;background:white;border:1px solid #a7b5c8;border-radius:5px}label{display:block;font-size:13px;margin-bottom:6px}.muted{color:#53647b;font-size:13px}table{border-collapse:collapse;width:100%;font-size:12px}th,td{padding:8px;text-align:left;border-bottom:1px solid #e1e6ed;vertical-align:top}th{background:#f2f5f9;position:sticky;top:0}.scroll{overflow:auto;max-height:460px}.badge{font-weight:600}.pass{color:#17724e}.fail{color:#af3434}.inconclusive,.unprofiled{color:#735722}svg{width:100%;height:auto}svg text{font:12px system-ui;fill:#42536a}svg circle{cursor:pointer}.tooltip{position:fixed;pointer-events:none;background:#17263c;color:white;padding:10px;border-radius:6px;white-space:pre-line;font-size:12px;max-width:430px;z-index:5}.legend{font-size:12px;line-height:1.6}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}details{margin-top:12px}a{color:#235da0}.warning{background:#fff5db;border-color:#e8c886}button{padding:8px;border:1px solid #a7b5c8;border-radius:5px;background:white;cursor:pointer}
</style>
<h1>GPU component evaluation</h1><p>Measured repeat medians and uncertainty, required clock coverage, component evidence and performance-preserving energy candidates.</p>
<div id="scope" class="card"></div>
<div class="bar"><div><label for="gpu">GPU</label><select id="gpu"></select></div><div><label for="workload">Component / function</label><select id="workload"></select></div><div style="flex:1"><label for="component">Input and measurement stratum</label><select id="component"></select></div><div><label for="objective">Energy objective</label><select id="objective"><option value="total">Whole-device total</option><option value="operational_idle_increment">Matched idle increment</option><option value="paired_active_reference">Paired active-reference contrast</option></select></div></div>
<div class="bar"><div><label for="memory">Plot memory domain</label><select id="memory"></select></div><div><label for="clock">Plot requested SM clock</label><select id="clock"></select></div></div><p id="policy" class="muted"></p>
<div id="cards" class="cards"></div><section><h2>Evaluation decision</h2><p id="decision"></p><div id="comparison"></div><details><summary>Input definition and measurement scope</summary><pre id="contract"></pre></details></section>
<section><div class="bar"><h2 style="flex:1">Measured response</h2><div><label for="view">View</label><select id="view"><option value="clock_rate">Clock vs sustained throughput</option><option value="clock_energy">Clock vs energy</option><option value="pareto">Throughput vs energy</option><option value="geometry">Issue resource vs throughput</option><option value="input_rate">Q vs throughput</option><option value="input_energy">Q vs energy</option><option value="power">One repeat: power over time</option><option value="temperature">One repeat: temperature over time</option></select></div><button id="export">Download SVG</button></div><div id="chart"></div><div class="legend">● NCU pass (green), × fail (red), □ inconclusive (amber), △ unprofiled (blue). Purple ring: advertised factory default fixed pair. Black ring: exact 1110 MHz. Large marker: selected candidate. Bars: bootstrap 95% intervals. Hover for clocks, geometry and quality. Points are observed; no interpolation across missing conditions.</div><p id="chartnote" class="muted"></p></section>
<section><h2>Clock and resource coverage</h2><div id="clocks" class="scroll"></div></section>
<section><h2>Conditions, uncertainty and rejected repeats</h2><div id="points" class="scroll"></div></section>
<section id="coalescingSection" hidden><h2>Memory read coalescing and experiment role</h2><p class="muted">Coalesced energy reads require a 1-word / 4-byte lane stride and sector-aligned full-warp geometry, plus bound sector-counter evidence near 100% efficiency. Target-path admission is separate. Efficiency is logical payload / counter-sector bytes: 25% means four times as many sector bytes. The counter scope identifies the memory level; L1/L2 sector efficiency is not HBM bus efficiency. Replay counters never rescale logical bandwidth or measured pJ. Explicit diagnostic experiments remain visible and cannot define energy optima or their observed peak.</p><div id="coalescing" class="scroll"></div></section>
<section id="inputScalingSection" hidden><h2>Q-scaling evidence</h2><p id="inputScalingScope" class="muted"></p><p id="inputScalingDecision" class="muted"></p><div id="inputScaling" class="scroll"></div><details><summary>Matched curve definitions and selected-candidate evidence</summary><pre id="inputScalingDetails"></pre></details></section>
<section><h2>Energy accounting and comparison checks</h2><p class="muted">Values below are repeat medians. Compare the same energy scope, unit, clock and input definition. A byte contains 8 bits; dense FMA counts as 2 FLOPs. Total/idle factors are observed scope differences, not correction coefficients. Unqualified contrasts remain diagnostic.</p><p id="selectionAccounting" class="muted"></p><div id="accounting" class="scroll"></div><details><summary>Same-window counts, reconstruction, sensor crosscheck and execution diagnostics</summary><pre id="accountingDetails"></pre></details></section>
<section id="latencySection" hidden><h2>Dependent-load latency: SM × address offset</h2><p class="muted">Cycles/access includes loop/address overhead and overlapping blocks. No near/far partition label is inferred. Frequencies are separated.</p><div id="latency" class="scroll"></div></section>
<section><h2>Profiler and numerical evidence</h2><p class="muted">Profiler rates describe replay busy time and are separate from the sustained energy experiment.</p><div id="evidence" class="scroll"></div><details><summary>Sampled numerical validation and profiler traffic rates</summary><pre id="numericEvidence"></pre></details></section>
<section><h2>Study acquisition coverage</h2><div id="coverage" class="scroll"></div><details><summary>Missing / mismatched trials and required-clock policy</summary><pre id="coverageDetails"></pre></details></section>
<section><h2>GPU comparison</h2><p class="muted">Rows retain their input definition, board scope and CUDA/cuBLAS versions. Compare equivalent definitions and resource scope; different SKU, footprint or toolkit rows are not pooled or ranked as identical experiments.</p><div id="comparisonTable" class="scroll"></div></section>
<section><h2>Interpretation limits</h2><div id="limits"></div></section><div id="tip" class="tooltip" hidden></div>
<script id="data" type="application/json">__EVALUATION_DATA__</script>
<script>
'use strict';
const data=JSON.parse(document.getElementById('data').textContent), $=id=>document.getElementById(id), fmt=x=>typeof x==='number'&&Number.isFinite(x)?x.toLocaleString(undefined,{maximumSignificantDigits:5}):'—', pct=x=>typeof x==='number'?fmt(100*x)+'%':'—', colors={pass:'#177c54',fail:'#bf4343',inconclusive:'#b48425',unprofiled:'#3e77b5'};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function table(id,headers,rows){const t=el('table'),h=el('tr');headers.forEach(v=>h.append(el('th',v)));t.append(h);rows.forEach(row=>{const tr=el('tr');row.forEach(v=>tr.append(el('td',typeof v==='object'?JSON.stringify(v):String(v??'—'))));t.append(tr)});$(id).replaceChildren(t)}
function options(id,values){$(id).replaceChildren(...values.map(([v,label])=>{const o=el('option',label);o.value=v;return o}))}
options('gpu',[...new Set(data.components.map(c=>c.stratum.gpu_uuid))].map(v=>[v??'',v??'Unknown GPU']));
function filterWorkload(){const cs=data.components.filter(c=>String(c.stratum.gpu_uuid??'')===$('gpu').value);options('workload',[...new Set(cs.map(c=>c.stratum.workload))].map(v=>[v,v]));filterComponent()}
function filterComponent(){const cs=data.components.filter(c=>String(c.stratum.gpu_uuid??'')===$('gpu').value&&c.stratum.workload===$('workload').value);options('component',cs.map(c=>[c.component_id,JSON.stringify(c.stratum.experiment_contract)+' · '+c.component_id]));render()}
const label=s=>String(s??'').replaceAll('_',' ');
const current=()=>data.components.find(c=>c.component_id===$('component').value);
const scale=(x,n)=>typeof x==='number'&&Number.isFinite(x)?x/n:null;
const rec=(c)=>c.recommendations.find(r=>r.objective===$('objective').value);
let previousWorkload=null;
function render(){const c=current();if(!c){$('decision').textContent='No measured component data';return}if(previousWorkload!==c.stratum.workload){$('objective').value=c.primary_objective||'total';previousWorkload=c.stratum.workload}const sfu=c.primary_objective==='paired_active_reference';for(const option of $('objective').options){option.textContent=({total:sfu?'Board total (diagnostic)':'Whole-device total',operational_idle_increment:sfu?'Idle increment (diagnostic)':'Matched idle increment',paired_active_reference:sfu?'Signed SFU / control contrast':'Paired active-reference contrast'})[option.value]}const o=$('objective').value,r=rec(c),u=c.units;
 const oldMemory=$('memory').value,oldClock=$('clock').value;options('memory',[['all','All observed domains'],...[...new Set(c.points.map(p=>p.requested_memory_mhz))].map(v=>[v??'incoming',v===null?'Incoming policy':v+' MHz'])]);options('clock',[['all','All observed clocks'],...[...new Set(c.points.map(p=>p.requested_graphics_mhz))].map(v=>[v??'incoming',v===null?'Incoming policy':v+' MHz'])]);if([...$('memory').options].some(x=>x.value===oldMemory))$('memory').value=oldMemory;if([...$('clock').options].some(x=>x.value===oldClock))$('clock').value=oldClock;$('policy').textContent='Throughput ≥ '+pct(data.policy.throughput_fraction)+' of the valid observed energy-population peak; ≥ '+data.policy.minimum_repeats+' valid repeats and ≥ '+data.policy.minimum_geometries+' verified geometries per clock; plateau: '+data.policy.minimum_resource_levels+(c.stratum.experiment_contract?.grid_mode==='auto'?' increasing Q levels at matched threads/clocks within ':' increasing issue-resource levels within ')+pct(data.policy.plateau_tolerance_fraction)+'; relative CI width ≤ '+pct(data.policy.maximum_relative_ci_width)+'.';$('contract').textContent=JSON.stringify(c.stratum,null,2);$('cards').replaceChildren(...[['Valid / rejected trials',(c.trial_counts.valid||0)+' / '+(c.trial_counts.invalid||0)],['Energy-population observed peak',fmt(scale(c.observed_peak,u.rate_scale))+' '+u.rate_unit],['Candidate energy',fmt(r?.energy)+' '+u.energy_unit],['Performance retained',pct(r?.throughput_fraction_of_observed_peak)]].map(([a,b])=>{const n=el('div',undefined,'card');n.append(el('div',a,'muted'),el('div',b,'value'));return n}));
 $('decision').textContent=c.interpretation+'. '+(c.primary_estimator?'Estimator: '+c.primary_estimator+'. ':'')+(c.correctness_scope||'')+'. '+label(r?.status||'No energy decision')+(r?.reason?': '+r.reason:'')+(r?.qualification_limits?.length?' — '+r.qualification_limits.join('; '):'');
 const comparisons=[r?.factory_default_comparison,r?.exact_1110_comparison].filter(Boolean);$('comparison').replaceChildren(...comparisons.map(v=>el('p',label(v.anchor)+': '+(v.status==='available'?'energy reduction '+pct(v.energy_reduction_fraction)+', throughput ratio '+fmt(v.throughput_ratio)+', '+label(v.evidence): v.reason),'muted')));
 table('clocks',['Requested SM / memory MHz','Observed peak ('+u.rate_unit+')','Verified peak','Verified geometries','Plateau evidence','Best total / idle / paired group'],c.clocks.map(k=>[k.graphics_mhz+' / '+k.memory_mhz,fmt(scale(k.observed_peak,u.rate_scale)),fmt(scale(k.verified_peak,u.rate_scale)),k.verified_geometry_count,label(k.plateau.status),k.minimum_energy_group_ids]));
 table('points',['Group / anchors','Experiment role','Requested / achieved SM MHz','Memory MHz','Geometry','Q / grid / count source','SFU signed contrast status','Repeats valid / rejected','NCU','Throughput ('+u.rate_unit+')','Energy ('+u.energy_unit+') / 95% CI','Energy per complete row (pJ/row)','Dense Tensor ceiling fraction','Contrast eligible','CI relative width / issues'],c.points.map(p=>[p.group_id+' '+p.anchor_tags.join(', '),p.experiment_role||'legacy_unspecified',p.requested_graphics_mhz+' / '+fmt(p.achieved_sm_mhz??p.achieved_graphics_mhz),p.requested_memory_mhz??'incoming policy',p.geometry,p.nonlinear_launch||p.sfu_launch,p.sfu_reference_delta,p.valid_repeats+' / '+p.rejected_repeats,p.ncu_status,fmt(scale(p.rate,u.rate_scale)),fmt(p.energies[o])+' / '+JSON.stringify(p.energy_ci95[o]),fmt(p.pj_per_row[o]),pct(p.tensor_dense_peak_fraction),p.objective_eligible[o],{widths:p.relative_ci_widths,issues:p.quality_issues,selection_reasons:p.eligibility_reasons?.[o]}]));
 const selectionCheck=c.energy_selection_diagnostics?.find(v=>v.objective===o);$('selectionAccounting').textContent=selectionCheck?'Whole-stratum selection check: lowest own-clock candidate '+fmt(selectionCheck.lowest_own_clock_candidate_energy)+' '+u.energy_unit+', performance relative to full-sweep peak '+pct(selectionCheck.own_clock_candidate_global_throughput_fraction)+'. Full-sweep performance constraint candidate '+fmt(selectionCheck.global_constraint_candidate_energy)+' '+u.energy_unit+'. '+selectionCheck.reason+'.':'Selection constraint accounting unavailable.';
 const filtered=c.points.filter(p=>($('memory').value==='all'||String(p.requested_memory_mhz??'incoming')===$('memory').value)&&($('clock').value==='all'||String(p.requested_graphics_mhz??'incoming')===$('clock').value));
 const memoryReads=filtered.filter(p=>p.memory_coalescing?.applicable);$('coalescingSection').hidden=!memoryReads.length;table('coalescing',['Group / role','Stride words / bytes','Offset / region bytes','Requested efficiency','Observed sector / logical bytes','Observed sector efficiency','Counter / scope','Target path','Coalescing / energy eligible','Peak population / reasons'],memoryReads.map(p=>{const g=p.memory_access_geometry||{},m=p.memory_coalescing;return[p.group_id+' / '+p.experiment_role,p.memory_stride_words+' / '+p.memory_lane_stride_bytes,g.offset_bytes+' / '+g.effective_region_bytes,pct(g.requested_sector_efficiency_fraction),fmt(m.observed_sector_bytes_per_logical_read_byte),pct(m.observed_sector_efficiency_fraction),(m.counter_name||'unavailable')+' / '+(m.counter_scope||'unknown'),p.ncu_status,m.status+' / '+p.memory_coalescing_energy_eligible,{included:p.energy_peak_population_eligible,reasons:m.reasons}]}));

 const inputCurves=c.input_scaling?.curves||[];$('inputScalingSection').hidden=!inputCurves.length;$('inputScalingScope').textContent=c.input_scaling?.scope||'';$('inputScalingDecision').textContent=Boolean(r?.saturation_evidence?.curve_id)?label(r.saturation_evidence.status)+': '+r.saturation_evidence.reason:'No selected candidate has Q-scaling qualification.';
 table('inputScaling',['Curve / group','Requested SM / memory MHz','Q (elements / SFU lanes)','Blocks / threads / SFU chains','Grid / count source','Throughput ('+u.rate_unit+')','Energy ('+u.energy_unit+')','Valid repeats / NCU','Curve evidence eligible / reasons'],inputCurves.flatMap(curve=>curve.rows.filter(p=>($('memory').value==='all'||String(p.requested_memory_mhz??'incoming')===$('memory').value)&&($('clock').value==='all'||String(p.requested_graphics_mhz??'incoming')===$('clock').value)).map(p=>[curve.curve_id+' / '+p.group_id,p.requested_graphics_mhz+' / '+p.requested_memory_mhz,fmt(p.input_elements),p.blocks+' / '+p.threads+' / '+(p.sfu_chains??'—'),p.grid_mode+' / '+p.block_completion_count_source,fmt(scale(p.rate,u.rate_scale)),fmt(p.energies[o]),p.valid_repeats+' / '+p.ncu_status,{eligible:p.eligible[o],reasons:p.eligibility_reasons[o]}])));$('inputScalingDetails').textContent=JSON.stringify({selected_candidate:r?.saturation_evidence,curves:inputCurves.map(v=>({curve_id:v.curve_id,signature:v.signature}))},null,2);

 table('accounting',['Group','Requested SM / memory MHz','Total W','Idle W','Idle fraction','Total / idle increment','Total / paired contrast','Total '+u.energy_unit,'Idle increment / qualified','Paired contrast / qualified','Sustained '+u.rate_unit,'Exact work / energy window'],filtered.map(p=>{const d=p.measurement_diagnostics||{},w=d.power_contributions||{},f=d.scope_factors||{};return[p.group_id,(p.requested_graphics_mhz??'incoming')+' / '+(p.requested_memory_mhz??'incoming'),fmt(w.total_w),fmt(w.idle_w),pct(w.idle_fraction),fmt(f.total_over_idle_increment),fmt(f.total_over_paired_reference),fmt(p.energies.total),fmt(p.energies.operational_idle_increment)+' / '+p.objective_eligible.operational_idle_increment,fmt(p.energies.paired_active_reference)+' / '+p.objective_eligible.paired_active_reference,fmt(scale(p.rate,u.rate_scale)),d.denominator?.exact_matching_window??'unknown']}));
 $('accountingDetails').textContent=JSON.stringify(filtered.map(p=>({group_id:p.group_id,measurement_diagnostics:p.measurement_diagnostics,sfu_reference_diagnostics:p.sfu_reference_diagnostics})),null,2);
 const evidence=c.profiler_evidence.flatMap(e=>e.checks.map(k=>[e.group_id,k.name,k.status,k.value,k.requirement]));table('evidence',['Group','Check','Status','Observed value','Requirement'],evidence);$('numericEvidence').textContent=JSON.stringify(c.profiler_evidence.filter(e=>e.sampled_numerical_checks.length||e.profile_rates.length||e.traffic_amplification?.length).map(e=>({group:e.group_id,numerical:e.sampled_numerical_checks,profiler_replay_rates:e.profile_rates,replay_traffic_amplification:e.traffic_amplification})),null,2);
 $('latencySection').hidden=!c.latency_points.length;
 if(c.latency_points.length){const buckets=new Map();c.latency_points.forEach(p=>{const key=JSON.stringify([p.graphics_mhz,p.memory_mhz,p.offset_bytes,p.sm_id]);if(!buckets.has(key))buckets.set(key,[]);buckets.get(key).push(p.cycles_per_access)});const offsets=[...new Set(c.latency_points.map(p=>p.offset_bytes))].sort((a,b)=>a-b),rows=new Map();for(const [key,values]of buckets){const [g,m,offset,sm]=JSON.parse(key),rk=g+'/'+m+' MHz · SM '+sm;if(!rows.has(rk))rows.set(rk,{});values.sort((a,b)=>a-b);rows.get(rk)[offset]=(values[Math.floor((values.length-1)/2)]+values[Math.floor(values.length/2)])/2}table('latency',['Clock / SM',...offsets.map(v=>'offset '+v+' B')],[...rows].map(([key,v])=>[key,...offsets.map(o=>fmt(v[o]))]));const cells=$('latency').querySelectorAll('td');const vals=c.latency_points.map(p=>p.cycles_per_access),low=Math.min(...vals),high=Math.max(...vals);cells.forEach(cell=>{const v=Number(cell.textContent.replaceAll(',',''));if(Number.isFinite(v)&&v>=low&&v<=high)cell.style.backgroundColor='hsl(210 65% '+(96-35*(v-low)/(high-low||1))+'%)'})}
 const all=data.components.filter(v=>v.stratum.workload===c.stratum.workload);table('comparisonTable',['GPU / name','Input definition','Toolkit versions','Candidate status','Primary '+u.energy_unit,'Observed '+u.rate_unit],all.map(v=>{const winner=v.recommendations.find(r=>r.objective===(v.primary_objective||'total'));return[v.stratum.gpu_uuid+' / '+v.gpu_name,v.stratum.experiment_contract,v.stratum.measurement_stratum?.runtime_versions,label(winner?.status),fmt(winner?.energy),fmt(scale(v.observed_peak,v.units.rate_scale))]}));plot(c,r)}
function svgNode(tag,attributes={}){const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attributes))n.setAttribute(k,String(v));return n}
function plot(c,r){$('tip').hidden=true;const o=$('objective').value,view=$('view').value,u=c.units,trace=view==='power'||view==='temperature';let xLabel,yLabel,points;
 if(trace){const source=c.measurement_example?.points||[],field=view==='power'?'power_w':'temperature_c',start=Math.min(...source.map(p=>p.t_s).filter(v=>typeof v==='number'));points=source.map(p=>({x:p.t_s-start,y:p[field],label:p.phase+'\n'+c.measurement_example.trial_id,status:'unprofiled'}));xLabel='Elapsed monotonic time (s)';yLabel=view==='power'?'Observed power (W)':'Temperature (°C)';$('chartnote').textContent=c.measurement_example?.note||'No raw telemetry example available.'}
 else if(view==='input_rate'||view==='input_energy'){points=(c.input_scaling?.curves||[]).flatMap(curve=>curve.rows.filter(p=>($('memory').value==='all'||String(p.requested_memory_mhz??'incoming')===$('memory').value)&&($('clock').value==='all'||String(p.requested_graphics_mhz??'incoming')===$('clock').value)).map(p=>({x:scale(p.input_elements,1e6),y:view==='input_energy'?(p.objective_measurement_valid[o]?p.energies[o]:null):scale(p.rate,u.rate_scale),ci:view==='input_energy'?p.energy_ci95[o]:p.rate_ci95?.map(v=>v/u.rate_scale),status:p.ncu_status,winner:p.group_id===r?.group_id,label:'curve '+curve.curve_id+'\ngroup '+p.group_id+'\nQ '+p.input_elements+', blocks/threads '+p.blocks+'/'+p.threads+'\nrequested SM/memory '+p.requested_graphics_mhz+'/'+p.requested_memory_mhz+' MHz\n'+p.grid_mode+'; '+p.block_completion_count_source+'\nevidence eligible: '+p.eligible[o]})));xLabel=c.primary_objective==='paired_active_reference'?'Q (million active SFU register lanes)':'Input Q (million elements)';yLabel=view==='input_energy'?u.energy_unit:u.rate_unit;$('chartnote').textContent='Matched Q curves only; each point keeps its own Q and energy. Curve IDs distinguish fixed threads and clocks. Observed size stability does not establish hardware saturation. The table reports evidence eligibility.'}
 else{points=c.points.filter(p=>($('memory').value==='all'||String(p.requested_memory_mhz??'incoming')===$('memory').value)&&($('clock').value==='all'||String(p.requested_graphics_mhz??'incoming')===$('clock').value)).map(p=>({x:view==='pareto'?scale(p.rate,u.rate_scale):view==='geometry'?p.resource_capacity:p.requested_graphics_mhz,y:view==='clock_energy'||view==='pareto'?p.energies[o]:scale(p.rate,u.rate_scale),ci:(view==='clock_energy'||view==='pareto'?p.energy_ci95[o]:p.rate_ci95?.map(v=>v/u.rate_scale)),p,status:p.ncu_status,label:p.group_id+'\nrequested SM/memory '+p.requested_graphics_mhz+'/'+p.requested_memory_mhz+' MHz\nachieved SM '+fmt(p.achieved_sm_mhz??p.achieved_graphics_mhz)+' MHz\n'+JSON.stringify(p.geometry)+'\nrole '+p.experiment_role+'; coalescing '+(p.memory_coalescing?.status??'not applicable')+'\nvalid/rejected '+p.valid_repeats+'/'+p.rejected_repeats,anchor:p.anchor_tags.includes('advertised_default_fixed_pair')?'factory':p.requested_graphics_mhz===1110?'1110':null,winner:p.group_id===r?.group_id})).filter(v=>!(view==='clock_energy'||view==='pareto')||v.p.objective_measurement_valid[o]);xLabel=view==='pareto'?u.rate_unit:view==='geometry'?(c.stratum.workload==='gemm'?'Tested GEMM problem work (m × n × k)':c.stratum.experiment_contract?.grid_mode==='auto'?'Launched grid threads; not simultaneous residency':'Tested issue-resource capacity'):'Requested graphics / SM clock (MHz)';yLabel=view==='clock_energy'||view==='pareto'?u.energy_unit:u.rate_unit;$('chartnote').textContent='Incoming-policy references appear in throughput/energy space; they have no fixed requested clock. Distinct memory domains and geometries are shown in tooltips. Valid diagnostic energy observations remain visible and do not establish energy winners. Valid signed SFU contrasts remain visible even when negative or zero-crossing. NCU colours show target-path evidence; coalescing eligibility is separate.'}
 points=points.filter(p=>typeof p.x==='number'&&Number.isFinite(p.x)&&typeof p.y==='number'&&Number.isFinite(p.y));const svg=svgNode('svg',{viewBox:'0 0 1100 420',role:'img','aria-label':xLabel+' versus '+yLabel});$('chart').replaceChildren(svg);if(!points.length){const t=svgNode('text',{x:80,y:100});t.textContent='No eligible observed points for this view';svg.append(t);return}
 let xmin=Math.min(...points.map(p=>p.x)),xmax=Math.max(...points.map(p=>p.x)),ymin=Math.min(...points.flatMap(p=>[p.y,...(p.ci||[])])),ymax=Math.max(...points.flatMap(p=>[p.y,...(p.ci||[])]));const dx=(xmax-xmin)||Math.abs(xmax)*.1||1,dy=(ymax-ymin)||Math.abs(ymax)*.1||1;xmin-=dx*.05;xmax+=dx*.05;ymin-=dy*.08;ymax+=dy*.08;const X=x=>85+(x-xmin)/(xmax-xmin)*965,Y=y=>355-(y-ymin)/(ymax-ymin)*300;
 function text(x,y,s){const t=svgNode('text',{x,y});t.textContent=s;svg.append(t)}
 for(let i=0;i<6;i++){const x=xmin+(xmax-xmin)*i/5,y=ymin+(ymax-ymin)*i/5;svg.append(svgNode('line',{x1:85,x2:1050,y1:Y(y),y2:Y(y),stroke:'#e2e7ee'}));text(8,Y(y)+4,fmt(y));text(X(x)-15,377,fmt(x))}text(420,410,xLabel);text(85,22,yLabel);
 for(const p of points){const color=colors[p.status]||'#8491a0',size=p.winner?7:4,x=X(p.x),y=Y(p.y);if(p.ci&&p.ci.every(Number.isFinite)){svg.append(svgNode('line',{x1:x,x2:x,y1:Y(p.ci[0]),y2:Y(p.ci[1]),stroke:color}));for(const v of p.ci)svg.append(svgNode('line',{x1:x-4,x2:x+4,y1:Y(v),y2:Y(v),stroke:color}))}if(p.anchor)svg.append(svgNode('circle',{cx:x,cy:y,r:size+4,fill:'none',stroke:p.anchor==='factory'?'#8424ae':'#17263c','stroke-width':2}));const n=p.status==='fail'?svgNode('path',{d:`M${x-size},${y-size}L${x+size},${y+size}M${x-size},${y+size}L${x+size},${y-size}`,stroke:color,'stroke-width':2}):p.status==='inconclusive'?svgNode('rect',{x:x-size,y:y-size,width:size*2,height:size*2,fill:color}):p.status==='unprofiled'?svgNode('path',{d:`M${x},${y-size}L${x+size},${y+size}L${x-size},${y+size}Z`,fill:color}):svgNode('circle',{cx:x,cy:y,r:size,fill:color});const title=svgNode('title');title.textContent=p.label+'\nx='+fmt(p.x)+', y='+fmt(p.y);n.append(title);n.addEventListener('pointermove',e=>{$('tip').hidden=false;$('tip').textContent=title.textContent;$('tip').style.left=Math.max(8,Math.min(e.clientX+15,innerWidth-440))+'px';$('tip').style.top=Math.min(e.clientY+15,innerHeight-180)+'px'});n.addEventListener('pointerleave',()=>{$('tip').hidden=true});svg.append(n)}}
 $('gpu').addEventListener('change',filterWorkload);$('workload').addEventListener('change',filterComponent);['component','objective','view','memory','clock'].forEach(id=>$(id).addEventListener('change',render));$('export').addEventListener('click',()=>{const svg=$('chart').querySelector('svg');if(!svg)return;const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml'}));const a=el('a');a.href=url;a.download='evaluation-'+current().component_id+'-'+$('view').value+'.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
 $('scope').textContent=(data.components.some(c=>String(c.gpu_name).toLowerCase().includes('synthetic'))?'SYNTHETIC VALIDATION FIXTURES — no hardware energy measurement. ':'')+'Acquisition coverage: '+data.coverage.status+'. '+(data.coverage.reason||'Required-clock policy and original plan checked.')+' Missing components: '+(data.missing_workloads.join(', ')||'none');if(data.coverage.status!=='complete')$('scope').classList.add('warning');table('coverage',['Component','Planned / observed trials','Missing','Rejected','Mismatched','Status'],Object.entries(data.coverage.by_workload).map(([w,c])=>[w,c.planned_trials+' / '+c.observed_trials,c.missing_trial_ids.length,c.invalid_trial_ids.length,c.mismatched_trial_ids.length,c.status]));$('coverageDetails').textContent=JSON.stringify(data.coverage,null,2);$('limits').replaceChildren(...data.limits.map(v=>el('p',v,'muted')));filterWorkload();
</script></html>'''
